using RestSharp;
using System;

namespace Tardigrade.Framework.RestSharp.Tests
{
    internal class TsaClient : RestSharpClient
    {
        public TsaClient(Uri endpoint) : base(endpoint)
        {
            var bearerToken = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjJkYzM4Yjc0LTFhNDAtMTFlYS05NzhmLTJlNzI4Y2U4ODEyNSIsInByaW1hcnlzaWQiOiI3NiIsIkVucm9sbWVudHM6Q3JlYXRlIjpbdHJ1ZSx0cnVlXSwiRW5yb2xtZW50czpMaXN0Ijp0cnVlLCJFbnJvbG1lbnRzOkRlc2NyaWJlIjp0cnVlLCJFbnJvbG1lbnRzOkRlbGV0ZSI6ZmFsc2UsIlN0dWRlbnRzOkNyZWF0ZSI6W3RydWUsdHJ1ZV0sIlN0dWRlbnRzOkxpc3QiOnRydWUsIlN0dWRlbnRzOkRlc2NyaWJlIjp0cnVlLCJTdHVkZW50czpEZWxldGUiOmZhbHNlLCJUcmFpbmluZ1BsYW5zOkNyZWF0ZSI6W2ZhbHNlLGZhbHNlXSwiVHJhaW5pbmdQbGFuczpMaXN0Ijp0cnVlLCJUcmFpbmluZ1BsYW5zOkRlc2NyaWJlIjp0cnVlLCJUcmFpbmluZ1BsYW5zOkRlbGV0ZSI6ZmFsc2UsIkNlcnRpZmljYXRlczpDcmVhdGUiOltmYWxzZSxmYWxzZV0sIkNlcnRpZmljYXRlczpMaXN0Ijp0cnVlLCJDZXJ0aWZpY2F0ZXM6RGVzY3JpYmUiOnRydWUsIkNlcnRpZmljYXRlczpEZWxldGUiOmZhbHNlLCJDZXJ0aWZpY2F0ZXM6RG93bmxvYWQiOnRydWUsIm5iZiI6MTU3NTg2NzYwOCwiZXhwIjo0NzMxNTQxMjA4LCJpYXQiOjE1NzU4Njc2MDgsImlzcyI6Imh0dHBzOi8vYXV0aC5zbW9vdGhsbXMuY29tLyIsImF1ZCI6Ii8ifQ.8vULtUIgRHQ4n46heniaH82Y4FjLkGwRpqNeX9Kzg_M";
            RestClient.AddDefaultHeader("Authorization", bearerToken);
        }
    }
}